services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: data
    ports:
      - "5432:5432"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  app:
    build : .
    container_name: learn_python
    depends_on :
      - postgres
      - kafka
    environment:
      DATABASE_URL: "postgresql://user:password@postgres_db:5432/stock_data"
      KAFKA_BROKER: "kafka:9092"
    volumes:
      - .:/app
    # command: ["python", "main.py"]/
    